### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by kavakhalil** [UmutAlihan/global-economy-scrapper#3]
Aşağıdaki line'dan kaynaklı list index out of range error'unu nasıl çözebiliriz?

tbody = soup('table', {"class":"alignRight data"})[0].find_all('tr')

**Error:**

runfile('/Users/halilkavak/Desktop/untitled0.py', wdir='/Users/halilkavak/Desktop')
Traceback (most recent call last):

  File "<ipython-input-15-e96e0e60b039>", line 1, in <module>
    runfile('/Users/halilkavak/Desktop/untitled0.py', wdir='/Users/halilkavak/Desktop')

  File "/Users/halilkavak/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/Users/halilkavak/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/halilkavak/Desktop/untitled0.py", line 14, in <module>
    tbody = soup('table', {"class":"alignRight data"})[0].find_all('tr')

IndexError: list index out of range

**Comment by UmutAlihan** [comment]
aşağıdaki function çıktı olarak bol list döndürüyor -> []
bunun içinde 0 index numaralı elementi istersen -> soup(....)[0]
out of range hatası verir
çünkü listende herhangi bir element bulamıyor :)

neden boş liste döndürdüğüne bakmak lazım

In [25]: soup('table', {"class":"alignRight data"})
Out[25]: []

**Comment by UmutAlihan** [comment]
Farklı bir yaklaşımla çözdüm sanırım

İlgili sitenin sağ üst kısmında, üllkenin ilgili tüm verilerini yıllara göre csv dosyasına indirme buttonu var. 

Oradaki linki çektim doğrudan...
